version: '3'

services:
  python3:
    container_name: python3
    build: 
      context: .
      dockerFile: Dockerfile
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./src:/root/opt
